/**
 * @import Libraries
 */
import {
    ApiProperty
} from '@nestjs/swagger';

/**
 * @import Dtos
 */
import {
    CreateOrderDeliveryDetailDto
} from './create.order-delivery_detail.dto';

export class CreateOrderDto {

    @ApiProperty({
        description: "The user that this order belongs to",
        example: "5ec72fd3cc15ca01220b3a8f",
        required: true
    })
    user_id: string;

    @ApiProperty({
        description: "A description of the order. This will be generated by the server",
        required: false
    })
    delivery_details?: CreateOrderDeliveryDetailDto;

}